### ISSUE TITLE
Midi-Recorder needs bpm-value-window

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#179] opened 2019-12-07 23:09 UTC
If I play my drumpatterns in loop mode it would be good to have a bpm-poti to play the rhythm faster or slower

**Comment by jofemodo** [comment] 2019-12-09 11:09
I've been testing jack-smf-player with jack transport, changing the BPMs, but it doesn't work. Reading the jack-smf-player code, i found this nice comment:

```
static int
sync_callback(jack_transport_state_t state, jack_position_t *position, void *notused)
{
	assert(jack_client);

	/* XXX: We should probably adapt to external tempo changes. */

	if (state == JackTransportStarting) {
		song_position = position->frame;
		smf_seek_to_seconds(smf, nframes_to_seconds(position->frame));

		if (!be_quiet)
			g_debug("Seeking to %f seconds.", nframes_to_seconds(position->frame));

		playback_started = jack_frame_time(jack_client);

	} else if (state == JackTransportStopped) {
		playback_started = -1;
	}

	return TRUE;
}
```

So, it look like we have some work to do ... ;-)

Regards,

**Comment by jofemodo** [comment] 2019-12-09 11:15
Ahh! For those interested in helping with this, jack-smf-utils code is here:

https://github.com/zynthian/jack-smf-utils

**Comment by Mickinator** [comment] 2019-12-09 13:49
👍🌈

von Norbert Schreiber gesendet

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Midi-Recorder needs bpm-value-window 
(#179)
Datum: 09.12.2019, 12:09 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

I've been testing jack-smf-player with jack transport, changing the BPMs, 
but it doesn't work. Reading the jack-smf-player code, i found this nice 
comment:

static int
sync_callback(jack_transport_state_t state, jack_position_t *position, void *notused)
{
	assert(jack_client);

	/* XXX: We should probably adapt to external tempo changes. */

	if (state == JackTransportStarting) {
		song_position = position->frame;
		smf_seek_to_seconds(smf, nframes_to_seconds(position->frame));

		if (!be_quiet)
			g_debug("Seeking to %f seconds.", nframes_to_seconds(position->frame));

		playback_started = jack_frame_time(jack_client);

	} else if (state == JackTransportStopped) {
		playback_started = -1;
	}

	return TRUE;
}

So, it look like we have some work to do ... ;-)

Regards,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/179?email_source=notifications&email_token=ANJNSQP7QIO73X7LD6YYJQ3QXYRN3A5CNFSM4JXTLO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIYW7Q#issuecomment-563186558> 
, or unsubscribe

**Comment by jofemodo** [comment] 2019-12-09 20:22
OK! jack-smf-player now support BPM changes:

https://github.com/zynthian/jack-smf-utils/issues/1

We can implement the tempo control in the MIDI recorder. It's a big step forward because zynthian will have a tempo line with transport control ... and this is the basic infrastructure for many new features ;-)

**Comment by Mickinator** [comment] 2019-12-10 00:18
Wow, Wow, wow,
I can't test it now, but tomorrow in the morning 😂😂😂🌈
You're great, so great, thank you very much !!!

**Comment by jofemodo** [comment] 2019-12-10 00:27
Nothing to test yet, my friend! I only implemented the feature in the "core" level. Now i have to implement it at the user level (UI).

**Comment by Mickinator** [comment] 2019-12-10 00:32
Ok, I will wait. But I'm so glad that I know you and your team and 
Zynthian grows (nearly every day).
I can't wait till tomorrow. But now I have to go to bed. I believe, I can't 
sleep 😂😂😂😂😂
Thanx, thanx, thanx




Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Midi-Recorder needs bpm-value-window 
(#179)
Datum: 10.12.2019, 01:27 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

Nothing to test yet, my friend! I only implemented the feature in the 
"core" level. Now i have to implement it at the user level (UI).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/179?email_source=notifications&email_token=ANJNSQJFSRFOHJ5NS6UDOZ3QX3O6TA5CNFSM4JXTLO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGLF6NY#issuecomment-563502903> 
, or unsubscribe

**Comment by jofemodo** [comment] 2019-12-12 12:31
You can test the new feature in the "zyntransport" branch.

**Comment by Mickinator** [comment] 2019-12-12 12:50
this night 👍😂🌈

von Norbert Schreiber gesendet

-----Original-Nachricht-----
Von: Jośe Fernando Moyano <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Midi-Recorder needs bpm-value-window 
(#179)
Datum: 12.12.2019, 13:31 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

You can test the new feature in the "zyntransport" branch.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/179?email_source=notifications&email_token=ANJNSQLZ5IXS3SU6E22OM5TQYIVJ5A5CNFSM4JXTLO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGWQPPQ#issuecomment-564987838> 
, or unsubscribe

**Comment by Mickinator** [comment] 2019-12-13 18:43
**Jofemodo:** You can test the new feature in the "zyntransport" branch.
**Mickinator:** Oh,I can´t find the "zyntransport branch"

Is there anybody who can help?

**Comment by mheidt** [comment] 2019-12-13 19:00
have you updated your zynthian?

**Comment by Mickinator** [comment] 2019-12-13 19:19
yes, several times




Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: mheidt <notifications@github.com <mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Midi-Recorder needs bpm-value-window 
(#179)
Datum: 13.12.2019, 20:00 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

have you updated your zynthian?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/179?email_source=notifications&email_token=ANJNSQJRKGDK6OKX5L2U5V3QYPLUVA5CNFSM4JXTLO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG25WPY#issuecomment-565566271> 
, or unsubscribe

**Comment by Mickinator** [comment] 2019-12-13 19:20
I use the buster image.



Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: mheidt <notifications@github.com <mailto:notifications@github.com> >
Betreff: Re: [zynthian/zynthian-ui] Midi-Recorder needs bpm-value-window 
(#179)
Datum: 13.12.2019, 20:00 Uhr
An: zynthian/zynthian-ui <zynthian-ui@noreply.github.com
<mailto:zynthian-ui@noreply.github.com> >
CC: Micki <norbert.schreiber@t-online.de
<mailto:norbert.schreiber@t-online.de> >, Author <
author@noreply.github.com <mailto:author@noreply.github.com> >

have you updated your zynthian?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zynthian/zynthian-ui/issues/179?email_source=notifications&email_token=ANJNSQJRKGDK6OKX5L2U5V3QYPLUVA5CNFSM4JXTLO22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG25WPY#issuecomment-565566271> 
, or unsubscribe

**Comment by jofemodo** [comment] 2019-12-13 22:17
You have to change the branch in webconf->repositories.
And update software ...

**Comment by Mickinator** [comment] 2019-12-14 11:35
I´ve changed Software/repositories/Zynthian-ui to zyntransport .
zynthian-webconf is on master.
Then i made an update -> Zynthian Display says "Error"
Then I made a roboot -> Zynthian Display says "Error"

After changing Zynthian-ui to master I could work again,but without bpm-cintrolling.

Do I have to change anything  in zynthian-webconf too?

**Comment by jofemodo** [comment] 2019-12-14 19:48
Yes. Please go to Hardware->Audio, click save and reboot.
I will try to find a way of including this in the update ...

**Comment by Mickinator** [comment] 2019-12-15 11:03
Hi Fernando,
now I have it. A lot of thanks.
But there is one problem: I recordet my drumpatterns with 80 bpm or 120 bpm. But if I playback my patterns, the speed is very low. With 360 bpm shown in the Zynthian-Display, it reaches max 60 bpm. I can´t go faster because 360 is the maximum. ...

**Comment by jofemodo** [comment] 2019-12-15 22:41
Please, send me one of your MIDI tracks. 

Thanks!

**Comment by Mickinator** [comment] 2019-12-16 10:38
Here is a track 
[Midi Track.zip](https://github.com/zynthian/zynthian-ui/files/3967542/Midi.Track.zip)

and here are 2 Examples:
the 1st is a normal pattern with zynthian-ui= master
and the 2nd is the speeddown-example beginning with 360 the 110 and the 360 again
[Zynthian.zip](https://github.com/zynthian/zynthian-ui/files/3967574/Zynthian.zip)

**Comment by jofemodo** [comment] 2019-12-17 00:24
It should be solved now ...

Regarding the "retrigger" problem, i can't reproduce it, sorry ...

**Comment by Mickinator** [comment] 2019-12-17 11:19
Hi Fernando,

yes, the bpm-controö works now. Thanks! This helps a lot :-)

Regarding the retrigger I´ve made a short video. Please excuse, my smartphone always stops recording automaticly ... I have more then 1 GB free space, but ....

The video shows, that when I´m using zynthian-ui: zyntransport (4fdea8d) the red frame jumps two rows up or down by pushing the up-down or select short-botton.

If I use the zynthian-ui:master everything works perfectly, but I have no speed-control (sorry, no vid)

[dobbletrig.zip](https://github.com/zynthian/zynthian-ui/files/3972953/dobbletrig.zip)

**Comment by jofemodo** [comment] 2019-12-17 16:53
Sorry, i can't reproduce your problem. MIDI control works perfectly for me. If i can't reproduce, i can't fix.

Regarding the first event problem, i've noted the "effect" and will try to solve it ... 
The error when stopping should be solved. Try updating again ...

**Comment by Mickinator** [comment] 2019-12-17 17:54
doubble trigger: bad luck, but things happend. I kow you give your very best. And I can´t solve it. So, lot of thanks. I believe the note-commands go two different ways to the midi-output. But I will controll this steps via Qwert-Keyboard.

Thanks a lot for solving the other probs.

**Comment by Mickinator** [comment] 2019-12-18 14:14
doubble trigger is solved, works now perfectly
Speed Control is ok.
noisy Sound by starting and stopping is not solved.

But: It goes foreward step by step. You are a magician in programming!
Thank you so much !!!

**Comment by Mickinator** [comment] 2019-12-19 12:16
Sorry, new problem
The Midi recorder drops the last tick of a trippled 4/4 track.
In the zip are wavs what show plaback via Zynthian and playback via PC.

[Sidestick.zip](https://github.com/zynthian/zynthian-ui/files/3983519/Sidestick.zip)

**Comment by jofemodo** [comment] 2019-12-20 17:44
Hi @Mickinator !
I'm closing this. Please, open a new issue for any related problem ...

**Closed by jofemodo** 2019-12-20 17:44 UTC
Labels: enhancement
