### ISSUE TITLE
Hotspot back to self-assigned address

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-ui#165] opened 2019-10-25 17:46 UTC
System: Rasperry Pi 4
Buster Image

When I check the Hotspot feature, the address 192.168.50.1 will  show in the network info for a short time.
After a couple of seconds, it falls back to a self-assigned address.

**Comment by jofemodo** [comment] 2019-10-30 16:56
I just tried with 2019-10-28-zynthianos-buster-lite-1.0.0.img and it's working like a charm for me. I can't reproduce the problem. 
I hope tomorrow's build will be green. Let's try with it and if it's working OK, we close the issue.

**Closed** 2019-11-15 10:55 UTC
Labels: Can't reproduce, bug
